runtime: python39

env_variables:
  FLASK_ENV: production
  DATABASE_URL: 'your-database-url-here'
  JWT_SECRET_KEY: 'your-secret-key-here'

handlers:
  - url: /api/.*
    script: auto
  - url: /.*
    static_files: index.html
    upload: index.html

